### ISSUE TITLE
no SQLite support

### ISSUE THREAD

**Issue by gentledepp** [wmeints/SyncFrameworkToolkit#4]
Hi! Sorry for contacting you this way.
I am currently playing around with syncwinrt.codeplexx.com. Essentially this is a syncframework extension to support sqlite on WinRT and WP8 devices.

As your port of the framework does not support this, I am planning to "copy" the implementation of syncwinrt and bring it to iOS and Android.

However - I am still new to the sync framework subject. So if you could give me some hints in how to do this, or even help me with porting the implementation, I would be very thankful
What do you think?

**Comment by wmeints** [comment]
Hi Gentledepp,

You are of course free to use another framework for your sync operations. 
As fun as it sounds to help you implement SQLite support for syncwinrt, I simply don't have the time to help you out. 

Please ping me on twitter ( @willem_meints ) if you have something to show :-)
